### ISSUE TITLE
Can't install package with pacman under container?

### ISSUE THREAD

**Issue by tmpm697** [nosada/mkosi-files#7]
Host OS: archlinux latest with linux-lts

sudo vi /etc/systemd/nspawn/buildspawn.nspawn:
```
[Exec]
PrivateUsers=true
NotifyReady=true

[Files]
# Bind=/ramdisk/scratch/:/scratch/

[Network]
# Private=yes
VirtualEthernet=no
```
when login to container I can be able to ping google.com, but when I try to do pacman -Syy to sync pacman db or try pacman -Sy fd for example, pacman failed with below error:
```
:: Synchronizing package databases...
error: failed to update core (no servers configured for repository)
error: failed to update extra (no servers configured for repository)
error: failed to update community (no servers configured for repository)
error: failed to synchronize all databases
```
I used latest and default configs in buildspawn folder.

**Comment by nosada** [comment]
@tmpm697 Thank you for your comment. I could reproduce. This is because there's no effective lines in `/etc/pacman.d/mirrorlist` on buildspawn:
```
[root@buildspawn builder]# grep -v '#' /etc/pacman.d/mirrorlist | sort | uniq

[root@buildspawn builder]#
```

I fixed this by https://github.com/nosada/mkosi-files/commit/f1bdcc7ed3e8d6482f674ec36948f4993ed52eb2, but you can also fix it by  uncommenting your favorite mirror(s) in `/etc/pacman.d/mirrorlist` on nspawn container by hand.

**Comment by tmpm697** [comment]
I copy mirrorlist from host to container and it worked.

But I tried your method and got this in mirrorlist in container:
```
Server = /$repo/os/$arch
```

**Comment by nosada** [comment]
Maybe `where-am-i` not installed anywhere in your `$PATH`. Would you try instruction in https://github.com/nosada/mkosi-files#how-to-use?

**Comment by tmpm697** [comment]
Ah, maybe I remove reflector from package. I'll test it later but it should work I suppose. Thanks.

**Comment by tmpm697** [comment]
When I run this command on host: `MIRROR=$(reflector --age 12 --sort age --country $(where-am-i) --protocol https --protocol http | grep Server | head -1 | cut -d ' ' -f 3 | cut -d '$$' -f 1)`

I got error:
```
cut: the delimiter must be a single character
Try 'cut --help' for more information.
error: no mirrors found
```

Remove `$` in `$$` gives me error:
```
error: no mirrors found
```
This dues to my country doesn't seem to list in mirror list :sad:


I think this is why `echo "Server = ${MIRROR}/\$$repo/os/\$$arch" > mkosi.extra/mirrorlist` doesn't work.


reflector service uses `reflector --protocol https --latest 30 --number 20 --sort rate` to get best result, I think this should be adapt instead of using country name.
```
MIRROR=$(reflector --protocol https --latest 30 --number 20 --sort rate | grep Server | head -1 | cut -d ' ' -f 3 | cut -d '$' -f 1)
```
should work, but I think keep number 20 instead of grep/head/cut to get only one inside container but `echo` command seem to expect only one line in `MIRROR`.

I think we can adapt using mirrorlist on host, run reflector each time building container costs time.

**Comment by tmpm697** [comment]
we should actually use `MIRROR=$(reflector --protocol https --latest 30 --number 1 --sort rate)`

**Comment by nosada** [comment]
I want to use fastest (located nearly where I'm in) and relatively-recently-synced mirror when `pacman -Syu` (& also `mkosi`), and that's why adding `--country $(where-am-i)` to reflector.

`reflector --protocol https --latest 30 --number 20 --sort rate` you specified gives us _relatevely-recently-synced_ mirrors but might not _fastest_ mirror. In other words, things like "Hey, reflector returns UK mirror but I'm in Japan!" would occur.

Reading your comment, I think below is so good too, because the user of this repo is expected using Arch :joy: 
> I think we can adapt using mirrorlist on host

**Comment by nosada** [comment]
Updated: https://github.com/nosada/mkosi-files/commit/d65a6c2f4d8b27345844d5643231636767e30f30

**Comment by nosada** [comment]
@tmpm697 Can I close this issue? I hope https://github.com/nosada/mkosi-files/issues/7#issuecomment-705347561 would solve your problem.

**Comment by tmpm697** [comment]
Thanks.
